// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb-JMUL9oIbGc48uxdYL7pA8ch06e62rM',
    appId: '1:252653844587:web:133d8ebba37f1d2ba5992e',
    messagingSenderId: '252653844587',
    projectId: 'todolist-b25b6',
    authDomain: 'todolist-b25b6.firebaseapp.com',
    storageBucket: 'todolist-b25b6.appspot.com',
    measurementId: 'G-X6DHCYTWKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJu95ncFBmBFd7WBGQ_euebXD6vW5siIc',
    appId: '1:252653844587:android:117a0edf06a493f5a5992e',
    messagingSenderId: '252653844587',
    projectId: 'todolist-b25b6',
    storageBucket: 'todolist-b25b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW3WssUKNpXer0N7UlVAFdFK9wHihkCz8',
    appId: '1:252653844587:ios:0664ef5cd11c3772a5992e',
    messagingSenderId: '252653844587',
    projectId: 'todolist-b25b6',
    storageBucket: 'todolist-b25b6.appspot.com',
    iosBundleId: 'com.example.apptodolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW3WssUKNpXer0N7UlVAFdFK9wHihkCz8',
    appId: '1:252653844587:ios:d51afe268f024f83a5992e',
    messagingSenderId: '252653844587',
    projectId: 'todolist-b25b6',
    storageBucket: 'todolist-b25b6.appspot.com',
    iosBundleId: 'com.example.apptodolist.RunnerTests',
  );
}
